### ISSUE TITLE
PPC/s390: V8 failing to build on ubuntu 16.04 (gcc 5.3)

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#5]
Failing with following error:
```
In file included from .././src/heap/store-buffer.h:12:0,
                 from .././src/heap/heap.h:21,
                 from ../src/heap/heap.cc:5:
.././src/heap/slot-set.h: In function 'void v8::internal::SlotSet::RemoveRange(int, int)':
.././src/heap/slot-set.h:197:42: error: array subscript is above array bounds [-Werror=array-bounds]
     uint32_t* cells = bucket[bucket_index];
                                          ^
.././src/heap/slot-set.h:103:60: error: array subscript is above array bounds [-Werror=array-bounds]
     if (current_bucket == kBuckets || bucket[current_bucket] == nullptr) {
                                                            ^
.././src/heap/slot-set.h:197:42: error: array subscript is above array bounds [-Werror=array-bounds]
     uint32_t* cells = bucket[bucket_index];
                                          ^

cc1plus: all warnings being treated as errors
```
on GCC 4.8.4 or earlier it builds cleanly.
Seems to be a known gcc bug
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59124

**Comment by jbajwa** [comment]
opened CL for this issue 
https://codereview.chromium.org/2256113002/
